# Generated by Django 5.0.3 on 2024-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_servicios_app', '0002_servicios_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='contenido',
            field=models.TextField(),
        ),
    ]
